import io
import logging
from PIL import Image
from app.schemas.ai import CivicDetectionResult, ProblemType, SeverityLevel
from app.services.vision_analyzer import VisionAnalyzer
from app.services.severity_engine import SeverityEngine
from app.services.department_resolver import DepartmentResolver

logger = logging.getLogger(__name__)

class LocalVisionProvider(VisionAnalyzer):
    """
    Local / Offline Vision Provider stub.
    Implements VisionAnalyzer to keep the AI provider replaceable without altering business logic.
    Identified explicitly as a demo fallback.
    """

    async def analyze(self, image_bytes: bytes, mime_type: str = "image/jpeg") -> CivicDetectionResult:
        logger.info(f"Running LocalVisionProvider fallback stub ({len(image_bytes)} bytes)")
        
        # Verify image integrity
        try:
            image = Image.open(io.BytesIO(image_bytes))
            image.verify()
        except Exception as e:
            return CivicDetectionResult(
                problem_type=ProblemType.OTHER,
                confidence=0.1,
                severity=SeverityLevel.LOW,
                evidence=["The uploaded file is not a valid or decodable image."],
                needs_retake=True,
                suggested_department=DepartmentResolver.resolve(ProblemType.OTHER),
                guidance_message="We couldn't clearly identify the civic issue. Please capture a clearer photo.",
                is_fallback=True
            )

        evidence = [
            "[DEMO FALLBACK] Demonstration road-surface defect identified",
            "[DEMO FALLBACK] Active traffic lane depression pattern"
        ]
        
        problem_type = ProblemType.POTHOLE
        confidence = 0.85
        severity = SeverityEngine.evaluate(problem_type, evidence)
        suggested_dept = DepartmentResolver.resolve(problem_type)

        return CivicDetectionResult(
            problem_type=problem_type,
            confidence=confidence,
            severity=severity,
            evidence=evidence,
            alternatives=["drain"],
            needs_retake=False,
            suggested_department=suggested_dept,
            guidance_message="[DEMO FALLBACK] AI estimation generated by local stub. Citizen can review and edit all fields.",
            is_fallback=True
        )
